name: CI

on:
  push:


jobs:
  testrelease:
    runs-on: ubuntu-latest

    steps:
    - run: echo "::set-env name=DATE::$(date '+%y%m%d%H%M%S')"
    - run: touch test.txt
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided by Actions but expires after 1h
      with:
        tag_name: v${{ env.DATE }}
        release_name: v${{ env.DATE }}
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: test.txt
        asset_name: test.txt
        asset_content_type: application/text
